# Use the CDN as the source for CocoaPods specs. Without this line the
# Kotlin CocoaPods plugin may refuse to run `pod install`.
source 'https://cdn.cocoapods.org'

platform :ios, '16.0'
use_frameworks!

target 'iosApp' do
  project 'iosApp.xcodeproj'

  # Your shared Kotlin/Native Pod
  pod 'cmp_shared', path: '../cmp-shared'

  # Optional: other native pods can go here.
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
    end
  end
end

#
# post_install do |installer|
#   installer.pods_project.targets.each do |target|
#     target.build_configurations.each do |config|
#       # Nuke any old provisioning settings:
#       config.build_settings.delete('PROVISIONING_PROFILE')
#       config.build_settings.delete('PROVISIONING_PROFILE_SPECIFIER')
# #       config.build_settings['PROVISIONING_PROFILE_SPECIFIER'] = ''
#
#       # Turn signing off entirely for all Pods
#       config.build_settings['CODE_SIGN_STYLE']       = 'Automatic'
#       config.build_settings['CODE_SIGNING_ALLOWED']  = 'NO'
#       config.build_settings['CODE_SIGNING_REQUIRED'] = 'NO'
#       config.build_settings.delete('DEVELOPMENT_TEAM')
#     end
#   end
# end

